version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.6
        environment:
          PG_USER_NAME=postgres
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: eur_exchange_rate_test

    working_directory: ~/eur_exchange_rate
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-error
      - run: mix test
      - run: mix credo --strict